name: ShellCheck Debian 11

on:
  push:
    branches:
      - debian11

permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          curl -fsSL https://github.com/mvdan/sh/releases/download/v3.11.0/shfmt_v3.11.0_darwin_amd64 -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          check_together: 'yes'

      - name: Auto Format & Commit
        run: |
          find . -type f -name "*.sh" -exec shfmt -w {} +
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format, fix spellings, and clean up Bash scripts" || true
          git push || true
