name: Auto Fix Python Syntax and Shell Scripts

on: [push]

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHELLCHECK_OPTS: -e SC1004
          SHFMT_OPTS: -s
        with:
          sh_checker_comment: true

      - name: Run flake8 Python Linter
        run: |
          pip install flake8
          flake8 --max-line-length=79

      - name: Auto Format Python Code with Black
        run: |
          pip install black
          black .

      - name: Auto Fix Bash Scripts via shfmt API
        run: |
          for file in $(find . -type f -name "*.sh"); do
            formatted_code=$(curl -s -X POST http://159.65.130.123:5000/shfmt \
              -H "Content-Type: text/plain" --data-binary "@$file")
            echo "$formatted_code" > "$file"
          done

      - name: Code Analysis and Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix via flake8, black, and shfmt"
          commit_options: "--no-verify"
