name: ShellCheck Debian 11

on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Auto Fix Bash Scripts via shfmt API
        run: |
          for file in $(find . -type f -name "*.sh"); do
            formatted_code=$(curl -s -X POST http://159.65.130.123:5000/shfmt \
              -H "Content-Type: text/plain" --data-binary "@$file")
            echo "$formatted_code" > "$file"
          done

      - name: Code Analysis
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix via shfmt API"
          commit_options: "--no-verify"
