name: ShellCheck Debian 11

on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install shfmt
        run: |
          curl -fsSL https://github.com/mvdan/sh/releases/download/v3.11.0/shfmt_v3.11.0_linux_amd64 -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Auto Fix Bash Scripts
        run: |
          for file in $(find . -type f -name "*.sh"); do
            shfmt "$file" -w -i 2 {} +
          done

      - name: Code Analysis
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix"
          commit_options: "--no-verify"