name: Auto Fix Python Syntax and Shell Scripts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AIOLint Linter
        uses: jonesroot/aiolint-action@3a30eab445b206419b618783cf3e8bd58f9c4ef9

      - name: Auto Commit Changes
        if: env.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix & Lint Bash via shfmt"
          commit_options: "--no-verify"
