name: Auto Fix Python Syntax and Shell Scripts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt

      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} +

      - name: Format Shell Scripts with shfmt
        run: |
          find . -type f -name "*.sh" -exec shfmt -w -i 2 {} +

      - name: Check for changes
        id: git-diff
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Auto Commit Changes
        if: env.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix & Lint Bash via shfmt"
          commit_options: "--no-verify"
