jobs:
  bash-auto-fix:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.7.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Fix Bash Scripts
        run: find . -type f -name "*.sh" -exec shfmt -w -i 2 {} +

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix Bash Scripts"
          commit_options: "--no-verify"
          file_pattern: "*.sh"
